name: Decide To Push Image(Frontend and backend images)
on:
  workflow_call:
    outputs:
      push_allowed:
        description: "true if image should be pushed"
        value: ${{ jobs.check.outputs.push_allowed }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      push_allowed: ${{ steps.result.outputs.push_allowed }}
    steps:
      - id: result
        env:
          BRANCH_REF: ${{ github.ref }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          set -euo pipefail
          allow="false"
          if [ "$BRANCH_REF" = "refs/heads/main" ] && \
             [ -n "${AZURE_CREDENTIALS:-}" ] && \
             [ -n "${ACR_LOGIN_SERVER:-}" ]; then
            allow="true"
          fi
          echo "push_allowed=$allow" >> "$GITHUB_OUTPUT"
          echo " Allow push: $allow"